#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: ${DB_URL}
#    username: ${USERNAME}
#    password: ${PASSWORD}
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
#        default_batch_fetch_size: 10
        highlight_sql: true

  application:
    name: recipe